const NAVIGATE_LOGIN="NAVIGATE_LOGIN";
const NAVIGATE_EDITOR="NAVIGATE_EDITOR"; 
const NAVIGATE_REGISTER="NAVIGATE_REGISTER";
const NAVIGATE_CREATE_DATA_SET="NAVIGATE_CREATE_DATA_SET";
const NAVIGATE_DATA_SET="NAVIGATE_DATA_SET";
const NAVIGATE_PUBLIC_DATA_SET="NAVIGATE_PUBLIC_DATA_SET";
const NAVIGATE_IMAGE_SET="NAVIGATE_IMAGE_SET";
const NAVIGATE_IMAGE_UPLOADER="NAVIGATE_IMAGE_UPLOADER"
;
const NAVIGATE_SETTINGS="NAVIGATE_SETTINGS";
module.exports={
NAVIGATE_LOGIN,
NAVIGATE_EDITOR,
NAVIGATE_REGISTER,
NAVIGATE_CREATE_DATA_SET,
NAVIGATE_DATA_SET,
NAVIGATE_PUBLIC_DATA_SET,
NAVIGATE_IMAGE_SET,
NAVIGATE_IMAGE_UPLOADER,
NAVIGATE_SETTINGS
}
